-- MySQL Script generated by MySQL Workbench
-- sam. 18 mars 2023 06:51:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema base_de_donnee_site_recrutement
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `base_de_donnee_site_recrutement` ;

-- -----------------------------------------------------
-- Schema base_de_donnee_site_recrutement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base_de_donnee_site_recrutement` DEFAULT CHARACTER SET utf8 ;
USE `base_de_donnee_site_recrutement` ;

-- -----------------------------------------------------
-- Table `base_de_donnee_site_recrutement`.`profils`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base_de_donnee_site_recrutement`.`profils` ;

CREATE TABLE IF NOT EXISTS `base_de_donnee_site_recrutement`.`profils` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `base_de_donnee_site_recrutement`.`candidats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base_de_donnee_site_recrutement`.`candidats` ;

CREATE TABLE IF NOT EXISTS `base_de_donnee_site_recrutement`.`candidats` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(20) NOT NULL,
  `mot_de_passe` VARCHAR(255) NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  `code_postal` VARCHAR(10) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `pays` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index2` (`email` ASC) VISIBLE,
  INDEX `index3` (`nom` ASC, `prenom` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `base_de_donnee_site_recrutement`.`recruteurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base_de_donnee_site_recrutement`.`recruteurs` ;

CREATE TABLE IF NOT EXISTS `base_de_donnee_site_recrutement`.`recruteurs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_entreprise` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `mot_de_passe` VARCHAR(255) NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  `code_postal` VARCHAR(10) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `pays` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index2` (`email` ASC) VISIBLE,
  INDEX `index3` (`nom_entreprise` ASC, `adresse` ASC, `mot_de_passe` ASC, `ville` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `base_de_donnee_site_recrutement`.`utilisateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base_de_donnee_site_recrutement`.`utilisateurs` ;

CREATE TABLE IF NOT EXISTS `base_de_donnee_site_recrutement`.`utilisateurs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `mot_de_passe` VARCHAR(255) NOT NULL,
  `profil_id` INT UNSIGNED NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `id_candidat_ou_recruteur` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `a` (`profil_id` ASC) VISIBLE,
  INDEX `fk_utilisateurs_1_idx` (`id_candidat_ou_recruteur` ASC) VISIBLE,
  INDEX `index4` (`email` ASC, `mot_de_passe` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateurs_avec_profils`
    FOREIGN KEY (`profil_id`)
    REFERENCES `base_de_donnee_site_recrutement`.`profils` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_utilisateurs_avec_cand`
    FOREIGN KEY (`id_candidat_ou_recruteur`)
    REFERENCES `base_de_donnee_site_recrutement`.`candidats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateurs_avec_recr`
    FOREIGN KEY (`id_candidat_ou_recruteur`)
    REFERENCES `base_de_donnee_site_recrutement`.`recruteurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `base_de_donnee_site_recrutement`.`offres_emploi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base_de_donnee_site_recrutement`.`offres_emploi` ;

CREATE TABLE IF NOT EXISTS `base_de_donnee_site_recrutement`.`offres_emploi` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_recruteur` INT UNSIGNED NOT NULL,
  `titre` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `date_publication` DATE NOT NULL,
  `date_limite` DATE NOT NULL,
  `ville_offre` VARCHAR(255) NOT NULL,
  `salaire` DECIMAL(10,2) NULL DEFAULT NULL,
  `email_recruteur` VARCHAR(45) NULL DEFAULT NULL,
  `type_travail` VARCHAR(45) NULL DEFAULT NULL,
  `experience` VARCHAR(45) NULL DEFAULT NULL,
  `niveau_etude` VARCHAR(45) NULL DEFAULT NULL,
  `nom_industrie` VARCHAR(45) NULL DEFAULT NULL,
  `categorie_travail` VARCHAR(45) NULL DEFAULT NULL,
  `images` VARCHAR(45) NULL DEFAULT NULL,
  `nom_societe` VARCHAR(45) NULL DEFAULT NULL,
  `site_internet` VARCHAR(45) NULL DEFAULT NULL,
  `numero_telephone` VARCHAR(45) NULL DEFAULT NULL,
  `email_entreprise` VARCHAR(45) NULL DEFAULT NULL,
  `adresse_entreprise` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_offres-emploi_recruteurs` (`id_recruteur` ASC) VISIBLE,
  INDEX `index3` (`date_publication` ASC, `date_limite` ASC, `ville_offre` ASC, `salaire` ASC, `titre` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_offres-emploi_recruteurs`
    FOREIGN KEY (`id_recruteur`)
    REFERENCES `base_de_donnee_site_recrutement`.`recruteurs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `base_de_donnee_site_recrutement`.`postulations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base_de_donnee_site_recrutement`.`postulations` ;

CREATE TABLE IF NOT EXISTS `base_de_donnee_site_recrutement`.`postulations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_offre` INT UNSIGNED NOT NULL,
  `id_candidat` INT UNSIGNED NOT NULL,
  `date_postulation` DATE NOT NULL,
  `lettre_motivation` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_postulations_offres_emploi` (`id_offre` ASC) VISIBLE,
  INDEX `fk_postulations_candidats` (`id_candidat` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_postulations_offres_emploi`
    FOREIGN KEY (`id_offre`)
    REFERENCES `base_de_donnee_site_recrutement`.`offres_emploi` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_postulations_candidats`
    FOREIGN KEY (`id_candidat`)
    REFERENCES `base_de_donnee_site_recrutement`.`candidats` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `base_de_donnee_site_recrutement`.`cv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base_de_donnee_site_recrutement`.`cv` ;

CREATE TABLE IF NOT EXISTS `base_de_donnee_site_recrutement`.`cv` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_candidat` INT UNSIGNED NOT NULL,
  `titre_profession` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `fichier_cv` VARCHAR(255) NOT NULL,
  `date_creation` DATE NOT NULL,
  `age` VARCHAR(45) NULL DEFAULT NULL,
  `ville` VARCHAR(45) NULL DEFAULT NULL,
  `sexe` VARCHAR(45) NULL DEFAULT NULL,
  `type_travail` VARCHAR(45) NULL DEFAULT NULL,
  `experience` VARCHAR(45) NULL DEFAULT NULL,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cv_candidats` (`id_candidat` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_cv_candidats`
    FOREIGN KEY (`id_candidat`)
    REFERENCES `base_de_donnee_site_recrutement`.`candidats` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_de_donnee_site_recrutement`.`competences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base_de_donnee_site_recrutement`.`competences` ;

CREATE TABLE IF NOT EXISTS `base_de_donnee_site_recrutement`.`competences` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `base_de_donnee_site_recrutement`.`candidats_competences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base_de_donnee_site_recrutement`.`candidats_competences` ;

CREATE TABLE IF NOT EXISTS `base_de_donnee_site_recrutement`.`candidats_competences` (
  `id_candidat` INT UNSIGNED NOT NULL,
  `id_competence` INT UNSIGNED NOT NULL,
  `niveau` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_candidat`, `id_competence`),
  INDEX (`id_competence` ASC) VISIBLE,
  CONSTRAINT `fk_candidat-competance_candidats`
    FOREIGN KEY (`id_candidat`)
    REFERENCES `base_de_donnee_site_recrutement`.`candidats` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidat-competance_competances`
    FOREIGN KEY (`id_competence`)
    REFERENCES `base_de_donnee_site_recrutement`.`competences` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `base_de_donnee_site_recrutement`.`offres_emploi_competences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base_de_donnee_site_recrutement`.`offres_emploi_competences` ;

CREATE TABLE IF NOT EXISTS `base_de_donnee_site_recrutement`.`offres_emploi_competences` (
  `id_offre` INT UNSIGNED NOT NULL,
  `id_competence` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_offre`, `id_competence`),
  INDEX `fk_off-emp-comp_comp` (`id_competence` ASC) VISIBLE,
  CONSTRAINT `fk_off-emp-comp_offr-emp`
    FOREIGN KEY (`id_offre`)
    REFERENCES `base_de_donnee_site_recrutement`.`offres_emploi` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_off-emp-comp_comp`
    FOREIGN KEY (`id_competence`)
    REFERENCES `base_de_donnee_site_recrutement`.`competences` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `base_de_donnee_site_recrutement`.`formations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base_de_donnee_site_recrutement`.`formations` ;

CREATE TABLE IF NOT EXISTS `base_de_donnee_site_recrutement`.`formations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cv` INT UNSIGNED NOT NULL,
  `nom_etablissement` VARCHAR(45) NULL DEFAULT NULL,
  `description_bref` VARCHAR(45) NULL DEFAULT NULL,
  `date_debut` DATE NULL DEFAULT NULL,
  `date_fin` DATE NULL DEFAULT NULL,
  `diplome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_formations_1_idx` (`id_cv` ASC) VISIBLE,
  INDEX `index3` (`nom_etablissement` ASC, `date_debut` ASC, `date_fin` ASC, `diplome` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_formations_cv`
    FOREIGN KEY (`id_cv`)
    REFERENCES `base_de_donnee_site_recrutement`.`cv` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_de_donnee_site_recrutement`.`experiances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base_de_donnee_site_recrutement`.`experiances` ;

CREATE TABLE IF NOT EXISTS `base_de_donnee_site_recrutement`.`experiances` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cv` INT UNSIGNED NOT NULL,
  `nom_societe` VARCHAR(45) NULL DEFAULT NULL,
  `poste` VARCHAR(45) NULL DEFAULT NULL,
  `nom_employeur` VARCHAR(45) NULL DEFAULT NULL,
  `description_bref` VARCHAR(45) NULL DEFAULT NULL,
  `date_debut` DATE NULL DEFAULT NULL,
  `date_fin` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_experiances_1_idx` (`id_cv` ASC) VISIBLE,
  INDEX `index3` (`nom_societe` ASC, `poste` ASC, `date_fin` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_experiances_cv`
    FOREIGN KEY (`id_cv`)
    REFERENCES `base_de_donnee_site_recrutement`.`cv` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
